---

- name: 'Run playbook-install_k3s.yml'
  ansible.builtin.import_playbook: playbook-install_k3s.yml

- name: 'Run playbook-cilium.yml'
  ansible.builtin.import_playbook: playbook-cilium.yml

- name: 'Run playbook-nginx.yml '
  ansible.builtin.import_playbook: playbook-nginx.yml
