---

- name: 'Gather facts'
  hosts: 'all'
  gather_facts: true

- name: 'Install Cilium'
  hosts: 'k3s1'
  gather_facts: false
  become: false
  module_defaults:
    kubernetes.core.helm:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s_info:
      kubeconfig: './k3s-kubeconfig'

  tasks:

    - name: 'Install Cilium via helm chart'
      # running this from vagrant fails, if we target localhost directly
      delegate_to: 'localhost'
      kubernetes.core.helm:
        chart_repo_url: 'https://helm.cilium.io/'
        release_name: 'cilium'
        chart_ref: 'cilium'
        release_namespace: 'kube-system'
        values:
          ipam:
            operator:
              clusterPoolIPv4PodCIDRList: "10.42.0.0/16"
          operator:
            replicas: 1

    - name: 'Wait until all pods are running'
      delegate_to: localhost
      become: false
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: kube-system
      register: pod_list
      until:
        '
        pod_list | json_query("resources[*].status.phase") | unique | sort == ["Running"]
        or
        pod_list | json_query("resources[*].status.phase") | unique | sort == ["Running", "Succeeded"]
        '
      retries: 24
      delay: 10

    - name: 'Wait until all pods are ready'
      delegate_to: localhost
      become: false
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: kube-system
        # there are two Job pods for installing Traefik via helm,
        # that are not ready, but '0/1 Completed'
        # we exclude them using the field_selectors
        field_selectors:
          - status.phase=Running
      register: pod_list_ready
      # pods with two containers show up as [true, true]
      until:
        '
        pod_list_ready | json_query("resources[*].status.containerStatuses[*].ready") | unique | sort == [[true]]
        or
        pod_list_ready | json_query("resources[*].status.containerStatuses[*].ready") | unique | sort == [[true], [true, true]]
        '
      retries: 12
      delay: 10
